"""testpilot init — Initialize a testpilot.yaml config in the current project."""

from __future__ import annotations
import os
from pathlib import Path
import typer
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel

console = Console()


def init_cmd(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing testpilot.yaml without prompting.",
    )
):
    """Initialize AI TestPilot X in the current directory.

    Creates [cyan]testpilot.yaml[/cyan] and a [cyan].testpilot/[/cyan] folder
    for databases and artifacts.
    """
    config_path = Path.cwd() / "testpilot.yaml"

    console.print()
    console.print(
        Panel.fit(
            "[bold cyan]AI TestPilot X[/bold cyan] · Project Setup", border_style="cyan"
        )
    )
    console.print()

    if config_path.exists() and not force:
        overwrite = Confirm.ask(
            "[yellow]testpilot.yaml already exists. Overwrite?[/yellow]", default=False
        )
        if not overwrite:
            console.print("[dim]Aborted — existing config kept.[/dim]")
            raise typer.Exit(0)

    # ── Collect settings ──────────────────────────────────────────────────────
    console.print("[bold]Step 1 of 3[/bold] — Gemini API Key")
    console.print("[dim]Get yours at: https://aistudio.google.com/app/apikey[/dim]")
    console.print()

    existing_key = os.environ.get("GEMINI_API_KEY", "")
    if existing_key and existing_key.startswith("AIzaSy"):
        console.print(
            f"[green]✓[/green] Found GEMINI_API_KEY in environment: "
            f"[dim]{existing_key[:12]}...[/dim]"
        )
        gemini_key = "${GEMINI_API_KEY}"
    else:
        gemini_key = Prompt.ask(
            "  Enter your Gemini API key (starts with AIzaSy)",
            password=True,
            default="${GEMINI_API_KEY}",
        )

    console.print()
    console.print("[bold]Step 2 of 3[/bold] — Target Application URL")
    target_url = Prompt.ask(
        "  Enter the URL of your application under test",
        default="https://your-app.com",
    )

    console.print()
    console.print("[bold]Step 3 of 3[/bold] — Execution Mode")
    console.print("  [dim]MOCK = simulated results (fast, no browser)[/dim]")
    console.print("  [dim]LOCAL = real Chrome on this machine[/dim]")
    console.print("  [dim]GRID = Selenium Grid (docker-compose up -d)[/dim]")
    execution_mode = Prompt.ask(
        "  Execution mode",
        choices=["MOCK", "LOCAL", "GRID"],
        default="MOCK",
    )

    # ── Write testpilot.yaml ──────────────────────────────────────────────────
    yaml_content = f"""# AI TestPilot X Configuration
# Generated by: testpilot init
# Docs: https://github.com/sagar-grv/ai-testpilot-x

# ── LLM Settings ──────────────────────────────────────────────────────────────
# Get your key at https://aistudio.google.com/app/apikey
gemini_api_key: {gemini_key}

# ── Test Execution ────────────────────────────────────────────────────────────
# MOCK = simulated | LOCAL = real Chrome | GRID = Selenium Grid
execution_mode: {execution_mode}

# Target application URL
target_url: {target_url}

# ── Storage ───────────────────────────────────────────────────────────────────
db_url: sqlite:///.testpilot/testpilot.db
chroma_path: .testpilot/chroma_db

# ── Output ────────────────────────────────────────────────────────────────────
output_dir: .testpilot/reports
log_level: WARNING

# ── Optional ──────────────────────────────────────────────────────────────────
# langsmith_api_key: ${{LANGSMITH_API_KEY}}
# langsmith_tracing: false
# max_agent_retries: 2
"""
    config_path.write_text(yaml_content, encoding="utf-8")

    # ── Create .testpilot/ directory structure ────────────────────────────────
    testpilot_dir = Path.cwd() / ".testpilot"
    for subdir in ["reports", "artifacts/screenshots", "artifacts/logs", "chroma_db"]:
        (testpilot_dir / subdir).mkdir(parents=True, exist_ok=True)

    # ── Add .testpilot/ to .gitignore ─────────────────────────────────────────
    gitignore = Path.cwd() / ".gitignore"
    gitignore_entry = "\n# AI TestPilot X\n.testpilot/\ntestpilot.yaml\n"
    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8")
        if ".testpilot" not in existing:
            with gitignore.open("a", encoding="utf-8") as f:
                f.write(gitignore_entry)
    else:
        gitignore.write_text(gitignore_entry, encoding="utf-8")

    # ── Success ───────────────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            "[green]✓[/green] [bold]AI TestPilot X initialized![/bold]\n\n"
            "[dim]Created:[/dim] [cyan]testpilot.yaml[/cyan]\n"
            "[dim]Created:[/dim] [cyan].testpilot/[/cyan] (reports, artifacts, db)\n"
            "[dim]Updated:[/dim] [cyan].gitignore[/cyan]\n\n"
            "[bold]Next steps:[/bold]\n"
            '  [cyan]testpilot run --story "User can login and checkout"[/cyan]\n'
            '  [cyan]testpilot analyze --story "User can reset password"[/cyan]\n'
            "  [cyan]testpilot dashboard[/cyan]  ← Launch visual UI",
            border_style="green",
            title="Setup Complete",
        )
    )
    console.print()
